import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, userEvent, within, waitFor } from "storybook/test";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { toast } from "@/lib/toast";

const meta = { title: "Legacy reference/Primitives/Overlays", component: Dialog, parameters: { pulse: { layout: "public", route: "/" }, layout: "padded" } } satisfies Meta<typeof Dialog>;
export default meta;
type Story = StoryObj<typeof meta>;
const Pad = ({ children }: { children: React.ReactNode }) => <div style={{ padding: 24, display: "flex", gap: 12, flexWrap: "wrap" }}>{children}</div>;
const opens = (name: RegExp) => async ({ canvasElement }: { canvasElement: HTMLElement }) => { await userEvent.click(within(canvasElement).getByRole("button", { name })); await waitFor(() => expect(document.querySelector('[role="dialog"], [role="alertdialog"], [role="menu"], [role="tooltip"]')).toBeTruthy()); };

export const DialogOpen: Story = { name: "Dialog", render: () => <Pad><Dialog><DialogTrigger asChild><Button>Request update</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Request an update from the inventor</DialogTitle><DialogDescription>Say what is missing. The inventor sees this note and the disclosure reopens for editing.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline">Cancel</Button><Button>Send request</Button></DialogFooter></DialogContent></Dialog></Pad>, play: opens(/Request update/) };
export const Confirmation: Story = { name: "Alert dialog", render: () => <Pad><AlertDialog><AlertDialogTrigger asChild><Button variant="destructive">Reject disclosure</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reject this disclosure?</AlertDialogTitle><AlertDialogDescription>Rejection is final for this revision. The inventor can appeal with a comment.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep reviewing</AlertDialogCancel><AlertDialogAction>Reject</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></Pad>, play: opens(/Reject disclosure/) };
export const Menu: Story = { name: "Dropdown menu", render: () => <Pad><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline">More actions</Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuLabel>Disclosure</DropdownMenuLabel><DropdownMenuItem>Clone</DropdownMenuItem><DropdownMenuItem>Download report</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem className="text-[var(--pulse-danger)]">Reject</DropdownMenuItem></DropdownMenuContent></DropdownMenu></Pad>, play: opens(/More actions/) };
export const PopoverOpen: Story = { name: "Popover", render: () => <Pad><Popover><PopoverTrigger asChild><Button variant="outline">Filter by status</Button></PopoverTrigger><PopoverContent><p className="text-sm">Filters go here.</p></PopoverContent></Popover></Pad>, play: opens(/Filter by status/) };
export const TooltipHover: Story = { name: "Tooltip", render: () => <Pad><Tooltip><TooltipTrigger asChild><Button variant="outline">Hover me</Button></TooltipTrigger><TooltipContent>Sends a reminder to the client. Once per 24 hours.</TooltipContent></Tooltip></Pad>, play: async ({ canvasElement }) => { await userEvent.hover(within(canvasElement).getByRole("button", { name: /Hover me/ })); await waitFor(() => expect(document.querySelector('[role="tooltip"]')).toBeTruthy()); } };
export const SideSheet: Story = { name: "Sheet", render: () => <Pad><Sheet><SheetTrigger asChild><Button>Manage access</Button></SheetTrigger><SheetContent><SheetHeader><SheetTitle>Manage access</SheetTitle><SheetDescription>Grant a case owner standing, temporary or step-in access to a client.</SheetDescription></SheetHeader></SheetContent></Sheet></Pad>, play: opens(/Manage access/) };
export const Toasts: Story = { render: () => <Pad><Button onClick={() => toast.success("Approved and sent to Photon Legal")}>Success toast</Button><Button variant="outline" onClick={() => toast.error("This change could not be saved. Please try again.")}>Error toast</Button></Pad>, play: async ({ canvasElement }) => { await userEvent.click(within(canvasElement).getByRole("button", { name: /Success toast/ })); await expect(await within(document.body).findByText(/Approved and sent/)).toBeInTheDocument(); } };
