import React from "react";
import { PRODUCT_CARD_TITLE_CLASS } from "@/components/ui/product-surfaces";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, Check, ChevronDown, ChevronRight, FileText, MoreHorizontal, Paperclip, PenLine, Search, Sparkles, X } from "lucide-react";
import { differenceInCalendarDays, format } from "date-fns";
import { Link } from "react-router-dom";
import API_CONFIG from "@/lib/apiConfig";
import { toast } from "@/lib/toast";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";

export type ReviewQueueStoryState = "typical" | "not-evaluated" | "long-title" | "already-decided" | "empty-queue" | "error" | "no-attachments-not-recommended" | "long-summary";
type View = "review" | "updates" | "counsel" | "all";
type Person = { id?: string; name?: string; email?: string };
type Idea = { id: string; title: string; summary?: string; about?: string; status: string; score?: number | null; submission_date?: string; sent_to_ip_committee_at?: string; updatedAt?: string; created_by?: string | Person; IdeaInventor?: Array<{ id: string; inventor?: Person }>; IdeaFiles?: Array<{ id: string; original_name?: string; file_path?: string }> };
type Draft = { id: string; title?: string; updatedAt?: string; meta_data?: Array<{ id: string; title: string; questions: Array<{ id: string; text: string; answer?: string }> }>; CheckDraftSoreLog?: Array<{ score?: number; score_meta_data?: { score?: number; scoringResult?: { summary?: string; closestMatches?: Array<{ analysis?: string }> }; priorArt?: unknown[] } }> };

const demoIdeas: Idea[] = [
  { id: "demo-1", title: "Thermal drift compensation for optical encoders in warehouse robots", summary: "We found that encoder readings drift as the drive assembly warms during a shift. Our controller measures that change locally and corrects the position signal while the robot keeps moving.", status: "SENT_TO_IHC", score: 81, submission_date: "2026-07-09", sent_to_ip_committee_at: "2026-07-11", created_by: { name: "Mateo Ruiz" }, IdeaInventor: [{ id: "1", inventor: { name: "Mateo Ruiz" } }, { id: "2", inventor: { name: "Aisha Khan" } }, { id: "3", inventor: { name: "Daniel Cho" } }], IdeaFiles: [{ id: "1", original_name: "Encoder test results.pdf" }, { id: "2", original_name: "Control loop diagram.png" }] },
  { id: "demo-2", title: "Collision-aware path smoothing using learned clearance maps", summary: "We train a clearance map from ordinary route data instead of maintaining a separate obstacle model. The planner uses it to smooth sharp corrections before they reach the drive controls.", status: "SENT_TO_IHC", score: 76, submission_date: "2026-08-01", created_by: { name: "Aisha Khan" } },
  { id: "demo-3", title: "Battery swap dock with passive alignment cones", summary: "We shaped the dock guides so a battery carrier corrects small approach errors using its own forward motion. The pack reaches the connector without adding cameras or powered alignment hardware.", status: "SENT_TO_IHC", score: 69, submission_date: "2026-08-10", created_by: { name: "Daniel Cho" }, IdeaFiles: [{ id: "3", original_name: "Dock tolerance study.pdf" }] },
  { id: "demo-4", title: "Load-adaptive grip surface for reusable shipping totes", summary: "We use the tote's own weight to change the contact profile of the gripping surface. Light and heavy loads can be handled by the same end effector without a powered adjustment step.", status: "SENT_TO_IHC", score: 63, submission_date: "2026-08-19", created_by: { name: "Priya Nair" }, IdeaFiles: [{ id: "4", original_name: "Grip cycle observations.pdf" }] },
  { id: "demo-5", title: "Self-indexing guide for modular conveyor junctions", summary: "We added a passive guide that brings replacement conveyor modules into alignment as their mounting bolts are tightened. Technicians can exchange a junction without laser alignment or a separate calibration fixture.", status: "SENT_TO_IHC", score: 58, submission_date: "2026-08-23", created_by: { name: "Owen Bell" }, IdeaFiles: [{ id: "5", original_name: "Junction assembly sketch.pdf" }] },
  { id: "demo-6", title: "Humidity-responsive seal for reusable cold-chain containers", summary: "We layer two ordinary seal materials so humidity changes their combined contact pressure. The lid stays easy to open when dry but seals more firmly as condensation develops.", status: "UPDATE_REQUEST", score: 47, submission_date: "2026-08-27", created_by: { name: "Elena García" } },
  { id: "demo-7", title: "Tool-free latch for replaceable sensor housings", summary: "We designed the housing latch to translate one thumb motion into both release and connector protection. A field technician can replace the sensor without exposing the contacts or carrying a dedicated tool.", status: "SEND_TO_OC", score: 34, submission_date: "2026-08-31", created_by: { name: "Noah Williams" }, IdeaFiles: [{ id: "6", original_name: "Housing prototype photos.pdf" }] },
];
const fixtureEvidence = "Local thermal history is the main differentiator; static temperature correction tables are well represented in the art.";
const demoDraft: Draft = {
  id: "draft-1",
  meta_data: [
    { id: "background", title: "Background", questions: [
      { id: "bg1", text: "What is the technological field of the invention?", answer: "The idea relates to optical position encoders used in autonomous material-handling equipment, particularly encoders mounted close to motors and gearboxes that experience changing temperatures during long shifts." },
      { id: "bg2", text: "What existing solutions or technologies are related to your idea?", answer: "Current systems use factory calibration tables, periodic homing routines, or a temperature reading taken elsewhere in the drive assembly. Those approaches either interrupt operation or do not represent the temperature at the sensing components." },
    ] },
    { id: "problem", title: "Problem", questions: [
      { id: "prob1", text: "What specific problem does your invention solve?", answer: "Heat changes the encoder reading during long shifts, causing placement errors and calibration stops." },
      { id: "prob2", text: "Why are current solutions inadequate?", answer: "A single static correction cannot account for warm-up, sustained load, and cooling periods. Remote temperature sensors also lag behind the encoder and can apply the right correction at the wrong time." },
    ] },
    { id: "solution", title: "Solution", questions: [
      { id: "sol1", text: "How does your invention work? Describe the core mechanism.", answer: "A local sensor feeds recent temperature history to a correction model in the encoder controller. It adjusts position continuously without stopping the robot." },
      { id: "sol2", text: "What are the key components or steps of your invention?", answer: "The system uses a local temperature sensor, a short rolling history, calibration coefficients stored per encoder, and a bounded correction stage between raw signal processing and the robot motion controller." },
      { id: "sol3", text: "What part do you believe is new?", answer: "The useful difference is the closed loop at the encoder itself: it observes local thermal behavior, applies a time-aware correction, and checks the corrected output against normal motion without requiring a stop or external reference fixture." },
    ] },
    { id: "advantages", title: "Advantages", questions: [
      { id: "adv1", text: "What advantages does your invention offer over existing solutions?", answer: "Robots can maintain placement accuracy through warm-up and heavy-duty cycles without scheduled homing. The correction remains local, so existing motion-control software receives the same position interface it already expects." },
      { id: "adv2", text: "Are there any potential cost, efficiency, or performance benefits?", answer: "Early tests reduced temperature-related placement error by roughly three quarters and avoided two calibration pauses per shift. The added sensor and controller storage cost less than replacing the encoder with a higher-grade unit." },
    ] },
    { id: "implementation", title: "Implementation", questions: [
      { id: "imp1", text: "How might this invention be implemented in practice?", answer: "During assembly, the encoder runs through a controlled warm-up while reference positions are recorded. The resulting coefficients are stored on the controller and refined within safe limits from later operating data." },
      { id: "imp2", text: "What resources would be needed to develop this invention?", answer: "We need three encoder variants, an environmental chamber, a reference stage, and firmware time from the controls team. The existing robot test cell can provide the long-duration duty cycles." },
      { id: "imp3", text: "What alternatives or variations should be covered?", answer: "The local measurement could use temperature, optical intensity, or another proxy for thermal state. The correction may be a lookup table, fitted equation, or constrained learned model, and it may run inside the encoder or an adjacent drive controller." },
    ] },
  ],
  CheckDraftSoreLog: [{ score: 81, score_meta_data: { score: 81, scoringResult: { summary: fixtureEvidence, closestMatches: [] }, priorArt: [] } }],
};
const lowDisclosureDraft: Draft = { ...demoDraft, id: "draft-low", meta_data: [{ id: "short", title: "Disclosure", questions: Array.from({ length: 5 }, (_, index) => ({ id: `short-${index}`, text: `Disclosure question ${index + 1}`, answer: "Inventor response." })) }] };
const when = (i: Idea) => i.sent_to_ip_committee_at || i.submission_date || i.updatedAt;
const ageInDays = (idea: Idea) => Math.max(0, differenceInCalendarDays(new Date(), new Date(when(idea) || Date.now())));
const ageTone = (days: number) => days > 30 ? "text-[var(--pulse-danger)]" : days >= 15 ? "text-[var(--pulse-brand-hover)]" : "text-[var(--pulse-ink-muted)]";
const name = (p?: string | Person) => typeof p === "string" ? p : p?.name || p?.email || "Unknown inventor";
const ten = (n?: number | null) => n == null ? null : n > 10 ? n / 10 : n;
const bandOf = (n?: number | null) => { const s = ten(n); return s == null ? "Not evaluated" : s >= 8 ? "Highly novel" : s >= 6 ? "Moderately novel" : s >= 4 ? "Marginally novel" : "Closely matched"; };
const withoutTitleLead = (sentence: string | undefined, title: string) => {
  const fallback = fixtureEvidence;
  if (!sentence) return fallback;
  if (!sentence.toLocaleLowerCase().startsWith(title.toLocaleLowerCase())) return sentence;
  const trimmed = sentence.slice(title.length).replace(/^[\s:,.—–-]+/, "");
  return trimmed ? `${trimmed[0].toUpperCase()}${trimmed.slice(1)}` : fallback;
};
const Avatar = ({ value }: { value: string }) => <span aria-hidden="true" className="grid h-7 w-7 place-items-center rounded-full bg-[var(--pulse-surface-subtle)] text-[10px] font-semibold">{value.split(/\s+/).slice(0, 2).map(w => w[0]).join("")}</span>;

const answerById = (draft: Draft | undefined, ids: string[]) => ids.map(id => draft?.meta_data?.flatMap(section => section.questions).find(question => question.id === id)?.answer?.trim()).filter(Boolean).join(" ");

type LifecycleStage = { label: string; detail?: string; state: "complete" | "current" | "upcoming" };
type ActivityEvent = { title: string; detail: string; date: string; icon: React.ComponentType<{ className?: string }> };
const lifecycleStages = (idea: Idea): LifecycleStage[] => {
  const current = idea.status === "GRANTED" ? 4 : idea.status === "FILED" ? 3 : idea.status === "SEND_TO_OC" ? 2 : ["UNDER_REVIEW", "SENT_TO_IHC", "UPDATE_REQUEST", "REJECT_BY_IHC", "REJECT_BY_OC"].includes(idea.status) ? 1 : 0;
  const labels = ["Submitted", "Under review", "Sent to Photon Legal", "Filed", "Granted"];
  const details = [idea.submission_date ? format(new Date(idea.submission_date), "MMM d, yyyy") : "Not recorded", idea.status === "UPDATE_REQUEST" ? "With inventor" : ["REJECT_BY_IHC", "REJECT_BY_OC"].includes(idea.status) ? "Review closed" : current === 1 ? "Decision needed" : undefined, current === 2 ? "In progress" : undefined, current < 3 ? "Usually 1 to 3 months" : undefined, undefined];
  return labels.map((label, index) => ({ label, detail: details[index], state: index < current || idea.status === "GRANTED" && index === 4 ? "complete" : index === current ? "current" : "upcoming" }));
};
const ReviewLifecycleTimeline = ({ idea }: { idea: Idea }) => <div className="mt-5 grid" style={{ gridTemplateColumns: "repeat(5, minmax(0, 1fr))" }} aria-label="Idea lifecycle">{lifecycleStages(idea).map((stage, index, all) => <div key={stage.label} className="relative min-w-0 pr-4 last:pr-0"><div className="relative flex h-5 items-center">{index < all.length - 1 && <span aria-hidden="true" className={`absolute left-5 right-0 top-1/2 -translate-y-1/2 ${stage.state === "complete" ? "h-px bg-[var(--pulse-success)]" : "border-t border-dashed border-[var(--pulse-line-strong)]"}`}/>}<span className={`relative z-10 grid h-5 w-5 place-items-center rounded-full ${stage.state === "complete" ? "bg-[var(--pulse-success)] text-white" : stage.state === "current" ? "bg-[var(--pulse-brand)] ring-4 ring-[var(--pulse-brand-soft)]" : "border border-[var(--pulse-line-strong)] bg-white"}`}>{stage.state === "complete" && <Check className="h-3 w-3"/>}</span></div><p className="mt-2 truncate text-[13px] font-semibold text-[var(--pulse-ink-secondary)]">{stage.label}</p>{stage.detail && <p className="mt-0.5 truncate text-xs text-[var(--pulse-ink-muted)]">{stage.detail}</p>}</div>)}</div>;

export default function ReviewQueueWorkspace({ storyState }: { storyState?: ReviewQueueStoryState }) {
  const qc = useQueryClient();
  const [view, setView] = React.useState<View>("review"), [search, setSearch] = React.useState(""), [selectedId, setSelectedId] = React.useState<string | null>(null), [tab, setTab] = React.useState<"brief" | "activity">("brief"), [expanded, setExpanded] = React.useState(false), [summaryExpanded, setSummaryExpanded] = React.useState(false), [mechanismExpanded, setMechanismExpanded] = React.useState(false), [dialog, setDialog] = React.useState<"send" | "request" | "reject" | null>(null), [note, setNote] = React.useState("");
  const query = useQuery({ queryKey: ["pulse-review-workspace"], enabled: !storyState, queryFn: async () => (await API_CONFIG.get("/api/v1/idea/fetch-by-user?page=1&limit=100&sort=submission_date&order=asc"))?.data });
  let ideas: Idea[] = storyState ? demoIdeas : Array.isArray(query.data?.data) ? query.data.data : [];
  if (storyState === "empty-queue") ideas = [];
  if (storyState === "long-title") ideas = [{ ...ideas[0], title: "Adaptive thermal drift compensation for high-precision optical encoders operating continuously across variable-temperature warehouse robotics environments" }, ...ideas.slice(1)];
  if (storyState === "already-decided") ideas = [{ ...ideas[0], status: "SEND_TO_OC" }, ...ideas.slice(1)];
  if (storyState === "no-attachments-not-recommended") ideas = [{ ...ideas[0], IdeaFiles: [] }, ...ideas.slice(1)];
  if (storyState === "long-summary") ideas = [{ ...ideas[0], summary: "We noticed that position readings become unreliable after the drive assembly has been working for several hours, even though the encoder itself remains within its published operating range. The error builds gradually and is difficult to distinguish from ordinary mechanical wear.\n\nWe added a small temperature measurement beside the encoder and use the recent thermal history to adjust the position signal before it reaches the motion controller. The correction runs continuously, so the robot does not need to pause for a calibration cycle.\n\nIn our tests, the same approach worked across several motor sizes after a short setup routine. We believe the useful part is the local self-correcting loop rather than any particular sensor or calibration table." }, ...ideas.slice(1)];
  const counts = { review: ideas.filter(i => ["UNDER_REVIEW", "SENT_TO_IHC"].includes(i.status)).length, updates: ideas.filter(i => i.status === "UPDATE_REQUEST").length, counsel: ideas.filter(i => i.status === "SEND_TO_OC").length, all: ideas.length };
  const filtered = ideas.filter(i => view === "all" || view === "review" && ["UNDER_REVIEW", "SENT_TO_IHC"].includes(i.status) || view === "updates" && i.status === "UPDATE_REQUEST" || view === "counsel" && i.status === "SEND_TO_OC").filter(i => `${i.title} ${name(i.created_by)}`.toLowerCase().includes(search.toLowerCase())).sort((a,b) => new Date(when(a) || 0).getTime() - new Date(when(b) || 0).getTime());
  React.useEffect(() => { if (!filtered.some(i => i.id === selectedId)) setSelectedId(filtered[0]?.id || null); }, [filtered, selectedId]);
  const selected = filtered.find(i => i.id === selectedId) || filtered[0] || null;
  React.useEffect(() => { setSummaryExpanded(false); setMechanismExpanded(false); }, [selected?.id, storyState]);
  const draftQuery = useQuery({ queryKey: ["pulse-review-drafts", selected?.id], enabled: Boolean(selected?.id) && !storyState, queryFn: async () => (await API_CONFIG.get(`/api/v1/idea/fetch-drafts/${selected!.id}`))?.data });
  const drafts: Draft[] = Array.isArray(draftQuery.data?.data) ? draftQuery.data.data : [];
  const draft = storyState === "no-attachments-not-recommended" ? lowDisclosureDraft : storyState ? demoDraft : drafts.at(-1), report = draft?.CheckDraftSoreLog?.at(-1)?.score_meta_data;
  const rawScore = storyState === "not-evaluated" ? null : storyState ? selected?.score : report?.score ?? draft?.CheckDraftSoreLog?.at(-1)?.score ?? selected?.score, score = ten(rawScore), band = bandOf(rawScore);
  const inventors = (selected?.IdeaInventor?.map(x => x.inventor).filter(Boolean) || []) as Person[], lead = inventors[0]?.name || name(selected?.created_by), submitter = name(selected?.created_by), decided = selected?.status === "SEND_TO_OC";
  const answerCount = draft?.meta_data?.reduce((total, section) => total + section.questions.filter(question => Boolean(question.answer?.trim())).length, 0) || 0;
  const attachmentCount = selected?.IdeaFiles?.length || 0;
  const recommended = ["Highly novel", "Moderately novel"].includes(band) && !(report?.scoringResult?.closestMatches || []).some(x => /cover/i.test(x.analysis || "")) && Boolean(draft?.meta_data?.length) && !(attachmentCount === 0 && answerCount < 6);
  const summary = selected?.summary || selected?.about || "No inventor summary was provided.";
  const summaryNeedsToggle = summary.length > 260 || summary.includes("\n\n");
  const problemAndMechanism = answerById(draft, ["prob1", "sol1"]) || "The inventor did not provide a problem and proposed mechanism.";
  const mechanismNeedsToggle = problemAndMechanism.length > 300;
  const activityEvents: ActivityEvent[] = [];
  if (selected && draft?.updatedAt) activityEvents.push({ title: "Draft updated", detail: draft.title || "Current draft", date: draft.updatedAt, icon: FileText });
  if (selected?.sent_to_ip_committee_at) activityEvents.push({ title: "Sent for committee review", detail: "Ready for an in-house counsel decision", date: selected.sent_to_ip_committee_at, icon: ArrowRight });
  if (selected?.submission_date) activityEvents.push({ title: "Disclosure submitted", detail: `Submitted by ${submitter}`, date: selected.submission_date, icon: PenLine });
  activityEvents.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  const refresh = () => Promise.all([qc.invalidateQueries({ queryKey: ["pulse-review-workspace"] }), qc.invalidateQueries({ queryKey: ["pulse-review-count"] })]);
  const send = useMutation({ mutationFn: () => API_CONFIG.post(`/api/v1/idea/send-to-oc/${draft?.id}/oc`, { instructions: "Approved by in-house counsel" }), onSuccess: async () => { toast.success("Sent to Photon Legal"); setDialog(null); await refresh(); } });
  const request = useMutation({ mutationFn: () => API_CONFIG.post(`/api/v1/idea/add-update-request/${selected?.id}`, { note: note.trim(), inventors: selected?.IdeaInventor?.map(x => x.inventor?.id).filter(Boolean) || [] }), onSuccess: async () => { toast.success("Changes requested"); setDialog(null); setNote(""); await refresh(); } });
  const reject = useMutation({ mutationFn: () => API_CONFIG.post(`/api/v1/idea/reject-from-ihc/${selected?.id}`, { reject_reason: note.trim() }), onSuccess: async () => { toast.success("Idea rejected"); setDialog(null); setNote(""); await refresh(); } });
  if (query.isPending && !storyState) return <div className="grid flex-1 place-items-center" role="status">Loading ideas…</div>;
  if (query.isError || storyState === "error") return <div className="grid flex-1 place-items-center"><div className="text-center"><h2 className="text-lg font-semibold">Couldn't load ideas.</h2><button type="button" onClick={() => query.refetch()} className="mt-3 h-9 rounded-sm border border-[var(--pulse-line)] bg-white px-4 [font:var(--pl-type-button-sm)] font-semibold">Retry</button></div></div>;
  const filters: Array<[View,string,number]> = [["review","Review",counts.review],["updates","Changes requested",counts.updates],["counsel","Sent to Photon Legal",counts.counsel],["all","All",counts.all]];

  return <div className="flex min-h-0 flex-1 overflow-hidden bg-white">
    <section className="flex w-[370px] shrink-0 flex-col border-r border-[var(--pulse-line)] xl:w-[410px]" aria-label="Ideas queue">
      <div className="border-b border-[var(--pulse-line)] p-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--pulse-ink-muted)]"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search title or inventor" className="h-10 w-full rounded-sm border border-[var(--pulse-line)] bg-[var(--pulse-surface-subtle)] pl-9 pr-9 [font:var(--pl-type-body-sm)] outline-none focus:bg-white focus-visible:ring-2 focus-visible:ring-[var(--pulse-focus)]"/>{search && <button type="button" onClick={() => setSearch("")} aria-label="Clear search" className="absolute right-2 top-1/2 -translate-y-1/2 p-1"><X className="h-4 w-4"/></button>}</div><div className="mt-3 flex items-center gap-2" aria-label="Queue filters">
        <button type="button" aria-pressed={view === "review"} onClick={() => setView("review")} className={`h-9 shrink-0 rounded-sm border px-3 [font:var(--pl-type-button-sm)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--pulse-focus)] ${view === "review" ? "border-[var(--pulse-ink)] bg-[var(--pulse-ink)] text-white" : "border-[var(--pulse-line)] text-[var(--pulse-ink-secondary)] hover:bg-[var(--pulse-surface-subtle)]"}`}>Review <span className="ml-1 tabular-nums">{counts.review}</span></button>
        <select aria-label="Other idea views" value={view === "review" ? "" : view} onChange={event => setView(event.target.value as View)} className="h-9 min-w-0 flex-1 rounded-sm border border-[var(--pulse-line)] bg-[var(--pulse-surface)] px-3 [font:var(--pl-type-button-sm)] text-[var(--pulse-ink-secondary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--pulse-focus)]">
          <option value="" disabled>Other views</option>
          {filters.filter(([key]) => key !== "review").map(([key,label]) => <option key={key} value={key}>{label}</option>)}
        </select>
      </div></div>
      <div className="grid grid-cols-[minmax(0,1fr)_max-content_max-content] gap-1 border-b border-[var(--pulse-line)] px-4 py-2 [font:var(--pl-type-field-label)] text-[var(--pulse-ink-muted)]"><span>Idea</span><span className="px-1.5 text-right">Score</span><span className="px-1.5 text-right">Age</span></div>
      <div className="min-h-0 flex-1 overflow-y-auto">{filtered.length ? filtered.map(idea => { const days = ageInDays(idea); const isSelected = selected?.id === idea.id; return <button key={idea.id} type="button" onClick={() => { setSelectedId(idea.id); setTab("brief"); }} className={`grid w-full grid-cols-[minmax(0,1fr)_max-content_max-content] gap-1 border-b border-[var(--pulse-line)] px-4 py-3.5 text-left transition-colors hover:bg-[var(--pulse-surface-subtle)] ${isSelected ? "bg-[var(--pulse-navy-soft)] shadow-[inset_2px_0_0_var(--pl-navy-2)]" : ""}`}><span className={`line-clamp-2 text-sm leading-5 text-[var(--pl-navy-2)] ${isSelected ? "font-semibold" : "font-medium"}`}>{idea.title}</span><span className="px-1.5 text-right text-sm font-medium tabular-nums text-[var(--pulse-ink-secondary)]">{ten(idea.score)?.toFixed(1) || "—"}</span><span className={`px-1.5 text-right text-sm font-medium tabular-nums ${ageTone(days)}`}>{days}d</span></button> }) : <div className="grid h-full min-h-60 place-items-center p-8 text-center"><div><h2 className="font-semibold">{search ? "No matching ideas." : "No ideas to review."}</h2><p className="mt-1 text-sm text-[var(--pulse-ink-muted)]">{search ? "Try a different title or inventor." : "Invite your team to submit their ideas."}</p>{!search && <Link to="/workspace" className="mt-4 inline-flex h-9 items-center rounded-sm bg-[var(--pulse-brand)] px-4 [font:var(--pl-type-button-sm)] font-semibold">Invite inventors</Link>}</div></div>}</div>
    </section>
    <section className="flex min-w-0 flex-1 flex-col">{!selected ? <div className="grid flex-1 place-items-center text-sm text-[var(--pulse-ink-muted)]">Select an idea</div> : <>
      <header className="border-b border-[var(--pulse-line)] px-6 pt-6"><h2 className="max-w-5xl [font:var(--pl-type-h2)] [letter-spacing:var(--pl-tracking-h2)]">{selected.title}</h2><div className="mt-3 flex flex-wrap items-center gap-2 text-sm text-[var(--pulse-ink-muted)]"><Avatar value={lead}/><DropdownMenu><DropdownMenuTrigger asChild><button type="button" className="font-medium text-[var(--pulse-ink-secondary)] hover:underline">{lead}{inventors.length > 1 ? ` +${inventors.length - 1}` : ""}</button></DropdownMenuTrigger><DropdownMenuContent align="start">{inventors.map((p,i) => <DropdownMenuItem key={`${p.id}-${i}`}>{p.name || p.email}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>{submitter !== lead && <span>Submitted by {submitter}</span>}<span>·</span><span>Submitted {selected.submission_date ? format(new Date(selected.submission_date), "d MMM yyyy") : "date unavailable"}</span></div>{decided && <div className="mt-4 border-y border-[var(--pulse-line)] bg-[var(--pulse-brand-soft)] px-3 py-2 text-sm font-medium">Sent to Photon Legal by Anita Rao, 2h ago</div>}<div className="mt-4 flex gap-6">{(["brief","activity"] as const).map(item => <button key={item} type="button" onClick={() => setTab(item)} className={`border-b-2 pb-3 [font:var(--pl-type-button-sm)] capitalize ${tab === item ? "border-[var(--pulse-ink)]" : "border-transparent text-[var(--pulse-ink-muted)]"}`}>{item}</button>)}</div></header>
      <div className="min-h-0 flex-1 overflow-y-auto bg-[var(--pulse-canvas)] px-6 py-5 [@media(max-height:760px)]:py-1"><div className="max-w-4xl space-y-4 [@media(max-height:760px)]:space-y-2">{tab === "brief" ? <>
        <section className="grid grid-cols-[112px_minmax(0,1fr)] items-start gap-6 rounded-md border border-[var(--pulse-line)] bg-white p-5 [box-shadow:var(--pulse-shadow-card)] [@media(max-height:760px)]:p-3"><div className="flex items-baseline gap-1.5 text-[var(--pl-navy-2)]"><span className="text-[28px] font-semibold leading-8 tabular-nums tracking-[-0.03em]">{score == null ? "—" : score.toFixed(1)}</span><span className="text-sm text-[var(--pulse-ink-muted)]">/ 10</span></div><div><p className="text-sm font-semibold text-[var(--pulse-success)]">{band}</p>{score != null && <><p className="mt-1 max-w-2xl text-sm font-normal leading-5 text-[var(--pulse-ink-secondary)]">{withoutTitleLead(report?.scoringResult?.summary, selected.title)}</p><p className="mt-3 inline-flex items-center gap-1 text-[13px] font-medium text-[var(--pulse-data-ai)]"><Sparkles className="h-3.5 w-3.5"/>AI evaluated <span aria-hidden="true">·</span> <Link to={`/ideas/${selected.id}?tab=ai-report`} className="inline-flex items-center gap-0.5 hover:text-[var(--pl-navy-2)]">Full evaluation <ChevronRight className="h-3.5 w-3.5"/></Link></p></>}</div></section>
        <section className="rounded-md border border-[var(--pulse-line)] bg-white p-5 [box-shadow:var(--pulse-shadow-card)] [@media(max-height:760px)]:p-3"><div><h3 className={PRODUCT_CARD_TITLE_CLASS}>What's new, according to the inventor</h3><p className={`mt-2 max-w-3xl whitespace-pre-line text-sm leading-5 text-[var(--pulse-ink-secondary)] ${summaryExpanded ? "" : "line-clamp-4"}`}>{summary}</p>{summaryNeedsToggle && <button type="button" onClick={() => setSummaryExpanded(current => !current)} aria-expanded={summaryExpanded} className="mt-1 text-[13px] font-semibold text-[var(--pulse-ink-secondary)]">{summaryExpanded ? "Less" : "More"}</button>}</div><div className="mt-4 border-t border-[var(--pulse-line)] pt-4 [@media(max-height:760px)]:mt-3 [@media(max-height:760px)]:pt-3"><h4 className="text-sm font-semibold text-[var(--pulse-ink)]">Problem and proposed mechanism</h4><p className={`mt-1.5 max-w-3xl text-sm leading-5 text-[var(--pulse-ink-secondary)] ${mechanismExpanded ? "" : "line-clamp-4"}`}>{problemAndMechanism}</p>{mechanismNeedsToggle && <button type="button" onClick={() => setMechanismExpanded(current => !current)} aria-expanded={mechanismExpanded} className="mt-1 text-[13px] font-semibold text-[var(--pulse-ink-secondary)]">{mechanismExpanded ? "Less" : "More"}</button>}</div></section>
        <section className="rounded-md border border-[var(--pulse-line)] bg-white p-5 [box-shadow:var(--pulse-shadow-card)] [@media(max-height:760px)]:p-3"><button type="button" onClick={() => setExpanded(!expanded)} aria-expanded={expanded} className="flex w-full items-center justify-between text-left"><span><span className={`block ${PRODUCT_CARD_TITLE_CLASS}`}>Invention disclosure</span>{!expanded && <span className="mt-1 block text-sm text-[var(--pulse-ink-muted)]">{answerCount} answers · {attachmentCount === 0 ? "no attachments" : `${attachmentCount} attachments`}</span>}</span>{expanded ? <ChevronDown className="h-5 w-5"/> : <ChevronRight className="h-5 w-5"/>}</button>{expanded && <div className="mt-6 space-y-6">{draft?.meta_data?.map(section => <div key={section.id}><h4 className="text-sm font-semibold">{section.title}</h4><dl className="mt-3 space-y-4">{section.questions.map(q => <div key={q.id}><dt className="text-xs font-medium text-[var(--pulse-ink-muted)]">{q.text}</dt><dd className="mt-1 text-sm leading-6">{q.answer || "—"}</dd></div>)}</dl></div>)}{selected.IdeaFiles?.map(file => <div key={file.id} className="flex items-center justify-between border-t border-[var(--pulse-line)] py-3 text-sm"><span className="flex items-center gap-2"><Paperclip className="h-4 w-4"/>{file.original_name || "Attachment"}</span><a href={file.file_path || "#"} className="font-semibold underline underline-offset-4">Open</a></div>)}</div>}</section>
      </> : <div className="py-8"><section><p className="text-xs font-semibold uppercase tracking-[0.08em] text-[var(--pulse-ink-muted)]">Lifecycle</p><h3 className="mt-2 text-lg font-semibold">Review progress</h3><ReviewLifecycleTimeline idea={selected}/></section><section className="mt-8 border-t border-[var(--pulse-line)] pt-6"><p className="text-xs font-semibold uppercase tracking-[0.08em] text-[var(--pulse-ink-muted)]">Audit trail</p><h3 className="mt-2 text-lg font-semibold">Recorded activity</h3><div className="mt-6">{activityEvents.map((event, index) => { const Icon = event.icon; return <div key={`${event.title}-${event.date}`} className="relative flex gap-4 pb-6 last:pb-0">{index < activityEvents.length - 1 && <span className="absolute left-[15px] top-8 h-[calc(100%-20px)] w-px bg-[var(--pulse-line)]"/>}<span className="relative z-10 grid h-8 w-8 shrink-0 place-items-center rounded-full border border-[var(--pulse-line)] bg-white"><Icon className="h-4 w-4 text-[var(--pulse-ink-muted)]"/></span><div className="min-w-0 pt-0.5"><p className="text-sm font-semibold">{event.title}</p><p className="mt-0.5 text-sm text-[var(--pulse-ink-muted)]">{event.detail}</p><p className="mt-1 font-mono text-xs text-[var(--pulse-ink-muted)]">{format(new Date(event.date), "MMM d, yyyy · h:mm a")}</p></div></div>})}</div></section></div>}</div></div>
      {!decided && <footer className="flex shrink-0 items-center justify-end gap-2 border-t border-[var(--pulse-line)] bg-white px-6 py-3"><DropdownMenu><DropdownMenuTrigger asChild><button type="button" aria-label="More actions" className="grid h-10 w-10 place-items-center rounded-sm border border-[var(--pulse-line)]"><MoreHorizontal className="h-4 w-4"/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => setDialog("reject")} className="text-[var(--pulse-danger)]">Reject idea</DropdownMenuItem></DropdownMenuContent></DropdownMenu><button type="button" onClick={() => setDialog("request")} className="h-10 rounded-sm border border-[var(--pulse-line)] px-4 text-sm font-semibold">Request changes</button><div className="relative">{recommended && <span title="Recommended: moderately novel, no prior art covers the core mechanism, disclosure complete" className="absolute bottom-[calc(100%+8px)] right-0 inline-flex h-7 items-center gap-1.5 whitespace-nowrap rounded-full border border-[var(--pulse-line-strong)] bg-white px-2.5 text-xs font-semibold text-[var(--pl-navy-2)]"><span className="h-1.5 w-1.5 rounded-full bg-[var(--pulse-brand)]"/>Recommended</span>}<button type="button" onClick={() => setDialog("send")} className="inline-flex h-10 items-center gap-2 rounded-sm bg-[var(--pulse-brand)] px-4 text-sm font-semibold shadow-[0_1px_0_rgba(0,0,0,0.08)] transition-colors hover:bg-[var(--pulse-brand-hover)]">Send to Photon Legal <ArrowRight className="h-4 w-4"/></button></div></footer>}
    </>}</section>
    <Dialog open={dialog !== null} onOpenChange={open => { if (!open) { setDialog(null); setNote(""); } }}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>{dialog === "send" ? "Send to Photon Legal for filing?" : dialog === "request" ? "Request changes" : "Reject idea"}</DialogTitle></DialogHeader>{dialog !== "send" && <div><label htmlFor="decision-note" className="text-sm font-semibold">{dialog === "request" ? "What should the inventor add or change?" : "Reason for the inventor"}</label><Textarea id="decision-note" required value={note} onChange={e => setNote(e.target.value)} className="mt-2 min-h-28" autoFocus/></div>}<DialogFooter><button type="button" onClick={() => setDialog(null)} className="h-10 px-4 [font:var(--pl-type-button-sm)] font-semibold">Cancel</button><button type="button" disabled={dialog !== "send" && !note.trim()} onClick={() => dialog === "send" ? send.mutate() : dialog === "request" ? request.mutate() : reject.mutate()} className={`h-9 rounded-sm px-4 [font:var(--pl-type-button-sm)] font-semibold disabled:opacity-50 ${dialog === "reject" ? "bg-[var(--pulse-danger)] text-white" : "bg-[var(--pulse-brand)]"}`}>{dialog === "send" ? "Send" : dialog === "request" ? "Send request" : "Reject idea"}</button></DialogFooter></DialogContent></Dialog>
  </div>;
}
