import type { Meta, StoryObj } from "@storybook/react-vite";
import { ProductChip } from "@/components/ui/product-chip";
import { PATENT_LEGAL_STATUS_META, PATENT_LEGAL_STATUS_VALUES } from "@/utils/patentLegalStatus";
import * as icons from "lucide-react";

/**
 * Foundations read production's current values: the CSS custom properties in
 * src/index.css and the type scale in tailwind.config.ts. DSN-0001 replaces
 * these with the token source; until then nothing here is a product change.
 */
const PULSE_VARS = ["--pulse-canvas", "--pulse-surface", "--pulse-surface-subtle", "--pulse-ink", "--pulse-ink-secondary", "--pulse-ink-muted", "--pulse-line", "--pulse-line-strong", "--pulse-brand", "--pulse-brand-hover", "--pulse-brand-soft", "--pulse-navy", "--pulse-navy-soft", "--pulse-focus", "--pulse-data-primary", "--pulse-data-accent", "--pulse-data-success", "--pulse-data-cyan", "--pulse-data-risk", "--pulse-data-ai", "--pulse-danger", "--pulse-danger-soft", "--pulse-success", "--pulse-success-soft", "--pulse-info", "--pulse-info-soft"];
const SHADCN_VARS = ["--background", "--foreground", "--card", "--popover", "--primary", "--primary-foreground", "--secondary", "--muted", "--muted-foreground", "--accent", "--accent-foreground", "--destructive", "--border", "--input", "--ring", "--sidebar-background", "--sidebar-primary", "--sidebar-accent"];
const Swatch = ({ name, value }: { name: string; value: string }) => <div style={{ display: "grid", gap: 6 }}><div style={{ height: 56, background: value, border: "1px solid var(--pulse-line)", borderRadius: 2 }} /><div style={{ font: "11px ui-monospace, monospace", color: "var(--pulse-ink-secondary)" }}>{name}</div><div style={{ font: "11px ui-monospace, monospace", color: "var(--pulse-ink-muted)" }}>{value}</div></div>;
const Grid = ({ children }: { children: React.ReactNode }) => <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(150px, 1fr))", gap: 16, padding: 24 }}>{children}</div>;
const H = ({ children }: { children: React.ReactNode }) => <h2 style={{ font: "600 14px/1.3 sans-serif", padding: "16px 24px 0", color: "var(--pulse-ink)" }}>{children}</h2>;

const meta = { title: "Legacy reference/Foundations/Tokens", parameters: { pulse: { layout: "public", route: "/" }, layout: "fullscreen" } } satisfies Meta;
export default meta;

export const Colors: StoryObj = { render: () => { const cs = getComputedStyle(document.documentElement); return <div><H>Pulse tokens (src/index.css)</H><Grid>{PULSE_VARS.map((v) => <Swatch key={v} name={v} value={cs.getPropertyValue(v).trim() || "unset"} />)}</Grid><H>shadcn tokens, HSL triplets</H><Grid>{SHADCN_VARS.map((v) => <Swatch key={v} name={v} value={`hsl(${cs.getPropertyValue(v).trim()})`} />)}</Grid></div>; } };
export const Typography: StoryObj = { render: () => <div style={{ padding: 24, display: "grid", gap: 14 }}>{[["text-2xl", "28/34 Page title"], ["text-xl", "22/28 Section title"], ["text-lg", "18/26 Card title"], ["text-base", "15/22 Body"], ["text-sm", "14/20 Secondary"], ["text-xs", "13/18 Label"]].map(([c, label]) => <div key={c} className={`${c} font-sans`}>{label} · The quick brown fox jumps over the lazy dog</div>)}<div className="font-mono text-sm">ACME-0007 · 17/842,391 · 2026-09-03 · monospace is for identifiers and records</div><div className="font-display text-xl font-semibold">Display face (currently the same family as body)</div></div> };
export const Spacing: StoryObj = { render: () => <div style={{ padding: 24, display: "grid", gap: 10 }}>{[1, 2, 3, 4, 5, 6, 8, 10, 12, 16].map((n) => <div key={n} style={{ display: "flex", alignItems: "center", gap: 12 }}><span style={{ font: "11px ui-monospace, monospace", width: 40, color: "var(--pulse-ink-muted)" }}>{n}</span><div style={{ height: 12, width: n * 4, background: "var(--pulse-brand)" }} /><span style={{ font: "11px ui-monospace, monospace", color: "var(--pulse-ink-muted)" }}>{n * 4}px</span></div>)}<div style={{ font: "12px sans-serif", color: "var(--pulse-ink-secondary)", marginTop: 8 }}>Radius: every rounded-* utility resolves to 2px in production; rounded-full stays circular.</div></div> };
export const StatusVocabulary: StoryObj = { name: "Status vocabulary", render: () => <div style={{ padding: 24, display: "grid", gap: 18 }}>
  <div><H>Idea states, as reviewers see them</H><div style={{ display: "flex", gap: 8, flexWrap: "wrap", padding: "8px 24px" }}>{[["Draft", "neutral"], ["Decision needed", "warning"], ["Waiting on inventor", "info"], ["Sent to Photon Legal", "info"], ["Filed", "success"], ["Declined", "danger"]].map(([l, t]) => <ProductChip key={l} tone={t as never}>{l}</ProductChip>)}</div></div>
  <div><H>Patent legal statuses (src/utils/patentLegalStatus.ts)</H><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))", gap: 8, padding: "8px 24px" }}>{PATENT_LEGAL_STATUS_VALUES.map((v) => <div key={v} style={{ display: "flex", gap: 8, alignItems: "center", font: "12px sans-serif" }}><span style={{ width: 8, height: 8, background: (PATENT_LEGAL_STATUS_META[v] as { marker?: string }).marker ?? "var(--pulse-ink-muted)" }} /><span>{PATENT_LEGAL_STATUS_META[v].label}</span><span style={{ font: "10px ui-monospace, monospace", color: "var(--pulse-ink-muted)" }}>{v}</span></div>)}</div></div>
</div> };
export const Icons: StoryObj = { render: () => <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(120px, 1fr))", gap: 12, padding: 24 }}>{["LayoutDashboard", "Lightbulb", "FileStack", "CalendarDays", "FolderKanban", "Building2", "UsersRound", "ClipboardCheck", "UserRound", "LogOut", "ArrowLeftRight", "Search", "Sparkles", "Check", "X", "MoreHorizontal", "PenLine", "Inbox", "FileText", "ArrowRight", "ArrowUpRight", "Plus", "Trash2", "Mail", "Upload", "Download", "Bell", "Info", "CircleCheck", "Loader2"].map((n) => { const I = (icons as Record<string, React.ComponentType<{ className?: string }>>)[n]; return I ? <div key={n} style={{ display: "grid", gap: 6, justifyItems: "center", font: "10px ui-monospace, monospace", color: "var(--pulse-ink-secondary)" }}><I className="h-5 w-5" />{n}</div> : null; })}</div> };
