// Generated by tools/tokens.mjs from src/styles/tokens.json (PL-TKN-004). Do not edit; edit the source and rerun.
export const sheet = "PL-TKN-004";
export const colors = {
  "pl": {
    "brand": "#F9B418",
    "brand-deep": "#DA9700",
    "brand-tint": "#FDF3DC",
    "navy": "#040410",
    "navy-2": "#11103C",
    "cream": "#F5F1E2",
    "ink": "#0C0C0C",
    "text-2": "#444444",
    "text-3": "#727272",
    "text-4": "#9C9C9C",
    "bg": "#FFFFFF",
    "bg-subtle": "#FAFAFA",
    "bg-muted": "#F5F5F5",
    "border": "#E8E8E8",
    "border-strong": "#C8C8C8",
    "green": "#1E7B4D",
    "green-tint": "#E9F1EC",
    "green-text": "#155C3B",
    "blue": "#4351C0",
    "blue-tint": "#ECEEF8",
    "blue-text": "#333F99",
    "red": "#B3362F",
    "red-tint": "#F7EDEB",
    "red-text": "#8E2B25",
    "amber-tint": "#FAF1DA",
    "amber-text": "#7E5A00",
    "slate": "#5E6470",
    "slate-tint": "#EFF0F2",
    "slate-text": "#484E59",
    "data-cyan": "#25A9B8",
    "data-ai": "#7057C7"
  },
  "photon": {
    "primary": "#F9B418",
    "primary-light-bg": "#FDF3DC",
    "light": "#DA9700",
    "dark": "#040410",
    "gray": {
      "100": "#FAFAFA",
      "200": "#F5F5F5",
      "300": "#E8E8E8",
      "400": "#C8C8C8",
      "500": "#9C9C9C",
      "600": "#727272",
      "700": "#444444",
      "800": "#0C0C0C"
    }
  }
} as const;
export const fontFamily = {
  "sans": [
    "Schibsted Grotesk",
    "system-ui",
    "sans-serif"
  ],
  "display": [
    "Newsreader",
    "Georgia",
    "serif"
  ],
  "mono": [
    "IBM Plex Mono",
    "ui-monospace",
    "monospace"
  ]
} as const;
export const type = {
  "display": {
    "font": "display",
    "weight": 600,
    "size": 56,
    "line": 64,
    "tracking": -0.8
  },
  "display-2": {
    "font": "display",
    "weight": 500,
    "size": 32,
    "line": 40,
    "tracking": 0
  },
  "h1": {
    "font": "ui",
    "weight": 600,
    "size": 28,
    "line": 36,
    "tracking": -0.28
  },
  "h1-serif": {
    "font": "display",
    "weight": 600,
    "size": 28,
    "line": 36,
    "tracking": -0.3
  },
  "h2": {
    "font": "ui",
    "weight": 600,
    "size": 22,
    "line": 30,
    "tracking": -0.11
  },
  "h3": {
    "font": "ui",
    "weight": 600,
    "size": 16,
    "line": 24,
    "tracking": 0
  },
  "card-title": {
    "font": "ui",
    "weight": 600,
    "size": 16,
    "line": 22,
    "tracking": 0
  },
  "body": {
    "font": "ui",
    "weight": 400,
    "size": 14,
    "line": 22,
    "tracking": 0
  },
  "body-sm": {
    "font": "ui",
    "weight": 400,
    "size": 13,
    "line": 20,
    "tracking": 0
  },
  "caption": {
    "font": "ui",
    "weight": 500,
    "size": 12,
    "line": 16,
    "tracking": 0.24,
    "transform": "uppercase"
  },
  "button": {
    "font": "ui",
    "weight": 600,
    "size": 14,
    "line": 18,
    "tracking": 0
  },
  "button-secondary": {
    "font": "ui",
    "weight": 500,
    "size": 14,
    "line": 18,
    "tracking": 0
  },
  "button-sm": {
    "font": "ui",
    "weight": 500,
    "size": 13,
    "line": 16,
    "tracking": 0
  },
  "link": {
    "font": "ui",
    "weight": 500,
    "size": 13,
    "line": 16,
    "tracking": 0
  },
  "field-label": {
    "font": "ui",
    "weight": 500,
    "size": 13,
    "line": 16,
    "tracking": 0
  },
  "help": {
    "font": "ui",
    "weight": 400,
    "size": 12,
    "line": 16,
    "tracking": 0
  },
  "metric-label": {
    "font": "ui",
    "weight": 500,
    "size": 13,
    "line": 16,
    "tracking": 0.3
  },
  "metric-value": {
    "font": "ui",
    "weight": 600,
    "size": 28,
    "line": 32,
    "tracking": 0
  },
  "mono": {
    "font": "mono",
    "weight": 400,
    "size": 13,
    "line": 20,
    "tracking": 0
  },
  "mono-label": {
    "font": "mono",
    "weight": 600,
    "size": 11,
    "line": 11,
    "tracking": 1,
    "transform": "uppercase"
  },
  "mono-meta": {
    "font": "mono",
    "weight": 400,
    "size": 11,
    "line": 11,
    "tracking": 0.8
  },
  "mono-delta": {
    "font": "mono",
    "weight": 600,
    "size": 12,
    "line": 14,
    "tracking": 0
  },
  "table-header": {
    "font": "mono",
    "weight": 600,
    "size": 11,
    "line": 14,
    "tracking": 0.8,
    "transform": "uppercase"
  },
  "table-cell-mono": {
    "font": "mono",
    "weight": 400,
    "size": 12,
    "line": 16,
    "tracking": 0
  },
  "kicker": {
    "font": "mono",
    "weight": 400,
    "size": 12,
    "line": 14,
    "tracking": 2,
    "transform": "uppercase"
  }
} as const;
export const radius = {
  "xs": "4px",
  "sm": "6px",
  "md": "8px",
  "lg": "12px",
  "full": "9999px"
} as const;
export const shadow = {
  "card": "none",
  "elevated": "none"
} as const;
export const roles = {
  "brand": "primary accent: calls to action, highlights, active states; never text",
  "brand-deep": "hover and pressed brand; text on brand tint",
  "brand-tint": "soft brand wash: callouts, selected rows",
  "navy": "deep brand ground: hero surfaces, footers",
  "navy-2": "elevated panels on navy",
  "cream": "warm editorial surface",
  "ink": "primary text, strongest interface ink",
  "text-2": "secondary text, body copy",
  "text-3": "tertiary text: captions, metadata",
  "text-4": "placeholder and disabled text",
  "bg": "base application background",
  "bg-subtle": "page sections, wells",
  "bg-muted": "inputs, hover, disabled",
  "border": "hairline dividers, card borders",
  "border-strong": "emphasised borders: inputs, tables, chips",
  "green": "status mark: approved, filed, success",
  "green-tint": "status wash",
  "green-text": "status text on white and on its tint",
  "blue": "status mark: in review, informational; the focus ring",
  "blue-tint": "status wash",
  "blue-text": "status text",
  "red": "status mark: rejected, overdue, destructive",
  "red-tint": "status wash",
  "red-text": "status text",
  "amber-tint": "status wash: waiting, changes requested; the mark is brand",
  "amber-text": "status text",
  "slate": "status mark: neutral, draft, closed",
  "slate-tint": "status wash",
  "slate-text": "status text",
  "data-cyan": "chart series only",
  "data-ai": "chart series and evaluation visuals only"
} as const;
export const space = {
  "1": "4px",
  "2": "8px",
  "3": "12px",
  "4": "16px",
  "5": "20px",
  "6": "24px",
  "8": "32px",
  "10": "40px",
  "1.5": "6px",
  "2.5": "10px",
  "3.5": "14px",
  "5.5": "22px"
} as const;
export const padding = {
  "tag": "6px 10px",
  "button": "11px 20px",
  "button-sm": "8px 14px",
  "input": "11px 14px",
  "card": "20px 22px",
  "cell": "14px 16px",
  "table-header": "12px 16px",
  "banner": "14px 18px"
} as const;
export const size = {
  "row-height": "48px",
  "marker": "7px",
  "banner-edge": "3px",
  "brand-rule": "3px",
  "caret": "1.5px"
} as const;
export const outline = {
  "hairline": {
    "value": "1px solid #E8E8E8",
    "offset": "-0.5px",
    "role": "cards, tables, metric cards, mono cards"
  },
  "strong": {
    "value": "1px solid #C8C8C8",
    "offset": "-0.5px",
    "role": "secondary buttons, status tags, inputs at rest"
  },
  "focus": {
    "value": "1.5px solid #4351C0",
    "offset": "-0.75px",
    "role": "focused inputs and controls"
  }
} as const;
export const source = {"file":"design/v4/PL-TKN-004.html","sha256":"548cc532b4d974d996f5ffe5b5c1556b19d24c1fd73e2947b6e315a12bb10a75","release":"v4.0 · 2026-08-18","status":"Approved"} as const;
