/**
 * Token generator (DSN-0001). Reads src/styles/tokens.json, the single token
 * source, and writes what the product reads:
 *   src/styles/tokens.css          --pl-* primitives, --pulse-* aliases, shadcn HSL
 *   src/styles/tokens.tailwind.ts  colour and font objects for tailwind.config.ts
 * Run `node tools/tokens.mjs` after editing the source and commit the outputs;
 * `node tools/tokens.mjs --check` fails when the outputs are stale.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(root, "src/styles/tokens.json");
const OUT_CSS = path.join(root, "src/styles/tokens.css");
const OUT_TW = path.join(root, "src/styles/tokens.tailwind.ts");

const t = JSON.parse(fs.readFileSync(SRC, "utf8"));
const HEADER = `Generated by tools/tokens.mjs from src/styles/tokens.json (${t.$sheet}). Do not edit; edit the source and rerun.`;

/** Resolve "{name}" references to primitive colours, shadows or fonts. */
function resolve(ref) {
  const m = /^\{([a-z0-9.-]+)\}$/.exec(String(ref));
  if (!m) return ref;
  const key = m[1];
  if (key.startsWith("shadow.")) return t.shadow[key.slice(7)].value;
  if (key.startsWith("font.")) return t.font[key.slice(5)].family;
  if (t.color[key]) return t.color[key].value;
  throw new Error(`unknown token reference ${ref}`);
}

/** #RRGGBB → "H S% L%" as shadcn expects. */
function hsl(hex) {
  const n = parseInt(hex.slice(1), 16);
  const r = ((n >> 16) & 255) / 255, g = ((n >> 8) & 255) / 255, b = (n & 255) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b), l = (max + min) / 2;
  if (max === min) return `0 0% ${Math.round(l * 100)}%`;
  const d = max - min;
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  let h = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
  h = Math.round(h * 60);
  return `${h} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

const entries = (o) => Object.entries(o).filter(([k]) => !k.startsWith("_") && !k.startsWith("$"));

function css() {
  const lines = [`/* ${HEADER} */`, "", ":root {"];
  lines.push("  /* Primitives: the sheet, verbatim */");
  for (const [k, v] of entries(t.color)) lines.push(`  --pl-${k}: ${v.value};${v._note ? " /* " + v._note + " */" : ""}`);
  for (const [k, v] of entries(t.font)) lines.push(`  --pl-font-${k}: ${v.family};`);
  for (const [k, v] of entries(t.radius)) lines.push(`  --pl-radius-${k}: ${v.value};`);
  for (const [k, v] of entries(t.shadow)) lines.push(`  --pl-shadow-${k}: ${v.value};`);
  lines.push("", "  /* Spacing, paddings and sizes from the specification's specimens */");
  for (const [k, v] of entries(t.space)) lines.push(`  --pl-space-${k.replace(".", "-")}: ${v};`);
  for (const [k, v] of entries(t.padding)) lines.push(`  --pl-pad-${k}: ${v};`);
  for (const [k, v] of entries(t.size)) lines.push(`  --pl-${k}: ${v};`);
  lines.push("", "  /* Outlines: surfaces are separated by inset hairlines, never shadows */");
  for (const [k, v] of entries(t.outline)) { lines.push(`  --pl-outline-${k}: ${v.value.replace(/\{([a-z0-9-]+)\}/g, (_, n) => resolve("{" + n + "}"))};`); lines.push(`  --pl-outline-${k}-offset: ${v.offset};`); }
  lines.push("", "  /* Type scale, as tokens; a screen record adopts a step */");
  for (const [k, v] of entries(t.type)) {
    lines.push(`  --pl-type-${k}: ${v.weight} ${v.size}px/${v.line}px var(--pl-font-${v.font});`);
    lines.push(`  --pl-tracking-${k}: ${v.tracking}px;`);
  }
  lines.push("", "  /* Aliases the components read (src/index.css before DSN-0001) */");
  for (const [k, v] of entries(t.aliases)) lines.push(`  --${k}: ${resolve(v)};`);
  lines.push("", "  /* shadcn theme, derived */");
  for (const [k, v] of entries(t.shadcn)) lines.push(`  --${k}: ${hsl(resolve(v))};`);
  lines.push(`  --radius: ${t.radius.sm.value};`);
  lines.push("}", "");
  return lines.join("\n");
}

function tailwind() {
  const pl = Object.fromEntries(entries(t.color).map(([k, v]) => [k, v.value]));
  const photon = {};
  for (const [k, v] of entries(t.tailwind.photon)) photon[k] = typeof v === "object" ? Object.fromEntries(Object.entries(v).map(([n, r]) => [n, resolve(r)])) : resolve(v);
  const stack = (family) => family.split(",").map((s) => s.trim().replace(/^"|"$/g, ""));
  const fontFamily = { sans: stack(t.font.ui.family), display: stack(t.font.display.family), mono: stack(t.font.mono.family) };
  const type = Object.fromEntries(entries(t.type).map(([k, v]) => [k, { font: v.font, weight: v.weight, size: v.size, line: v.line, tracking: v.tracking, ...(v.transform ? { transform: v.transform } : {}) }]));
  const body = [
    `// ${HEADER}`,
    `export const sheet = ${JSON.stringify(t.$sheet)};`,
    `export const colors = ${JSON.stringify({ pl, photon }, null, 2)} as const;`,
    `export const fontFamily = ${JSON.stringify(fontFamily, null, 2)} as const;`,
    `export const type = ${JSON.stringify(type, null, 2)} as const;`,
    `export const radius = ${JSON.stringify(Object.fromEntries(entries(t.radius).map(([k, v]) => [k, v.value])), null, 2)} as const;`,
    `export const shadow = ${JSON.stringify(Object.fromEntries(entries(t.shadow).map(([k, v]) => [k, v.value])), null, 2)} as const;`,
    `export const roles = ${JSON.stringify(Object.fromEntries(entries(t.color).map(([k, v]) => [k, v.role])), null, 2)} as const;`,
    `export const space = ${JSON.stringify(Object.fromEntries(entries(t.space)), null, 2)} as const;`,
    `export const padding = ${JSON.stringify(Object.fromEntries(entries(t.padding)), null, 2)} as const;`,
    `export const size = ${JSON.stringify(Object.fromEntries(entries(t.size)), null, 2)} as const;`,
    `export const outline = ${JSON.stringify(Object.fromEntries(entries(t.outline).map(([k, v]) => [k, { value: v.value.replace(/\{([a-z0-9-]+)\}/g, (_, n) => resolve("{" + n + "}")), offset: v.offset, role: v.role }])), null, 2)} as const;`,
    `export const source = ${JSON.stringify(t.$source)} as const;`,
    "",
  ];
  return body.join("\n");
}

const outputs = [[OUT_CSS, css()], [OUT_TW, tailwind()]];
if (process.argv.includes("--check")) {
  const stale = outputs.filter(([file, text]) => !fs.existsSync(file) || fs.readFileSync(file, "utf8") !== text).map(([f]) => path.relative(root, f));
  if (stale.length) { console.error(`tokens: stale outputs ${stale.join(", ")}; run node tools/tokens.mjs`); process.exit(1); }
  console.log("tokens: outputs match the source");
} else {
  for (const [file, text] of outputs) fs.writeFileSync(file, text);
  console.log(`tokens: wrote ${outputs.map(([f]) => path.relative(root, f)).join(" and ")}`);
}
